apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
  labels:
    app: static-website
spec:
  # Maintains exactly 3 running replicas of your container at all times
  replicas: 3
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: nginx-container
        # The image you pushed during the CI phase
        image: subhani8189/my_portifilio-portfolio-web:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        
        # --- AUTO-HEALING: Liveness Probe ---
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          
        # --- TRAFFIC CONTROL: Readiness Probe ---
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: static-website-loadbalancer
spec:
  # Provisions a cloud load balancer to route traffic to your pods
  type: LoadBalancer
  selector:
    app: static-website 
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80